---
include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    cancel_subscriptions: true
    prefer_single_quotes: true

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: warning
