---
name: prime
description: >-
  A library of useful, reusable, methods and extensions for Dart.

  See also `flutter_prime` for Flutter apps.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/prime
issue_tracker: https://github.com/GizmosDev/prime/issues

version: 0.1.0-alpha.6

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  intl: ^0.20.1
  characters: ^1.4.0

dev_dependencies:
  # Linting
  lints: ^5.1.0

  # Building
  dependency_validator: ^5.0.2

  # Testing
  test: ^1.25.13
  coverage: ^1.11.1
